// Static seed lists for autocomplete -- merged at the UI layer with whatever the account has
// actually logged before (see /api/facets), so suggestions improve with real usage on top of
// this generic starting point.

export const COMMON_EXERCISES = [
  "Barbell Squat",
  "Front Squat",
  "Goblet Squat",
  "Bulgarian Split Squat",
  "Leg Press",
  "Leg Extension",
  "Leg Curl",
  "Romanian Deadlift",
  "Deadlift",
  "Sumo Deadlift",
  "Hip Thrust",
  "Walking Lunge",
  "Calf Raise",
  "Bench Press",
  "Incline Bench Press",
  "Decline Bench Press",
  "Dumbbell Bench Press",
  "Dumbbell Fly",
  "Push-up",
  "Dip",
  "Overhead Press",
  "Arnold Press",
  "Lateral Raise",
  "Front Raise",
  "Face Pull",
  "Pull-up",
  "Chin-up",
  "Lat Pulldown",
  "Barbell Row",
  "Dumbbell Row",
  "Seated Cable Row",
  "T-Bar Row",
  "Bicep Curl",
  "Hammer Curl",
  "Preacher Curl",
  "Tricep Pushdown",
  "Skull Crusher",
  "Overhead Tricep Extension",
  "Plank",
  "Hanging Leg Raise",
  "Cable Crunch",
  "Russian Twist",
  "Farmer's Carry",
  "Kettlebell Swing",
  "Clean and Jerk",
  "Snatch",
  "Power Clean",
  "Box Jump",
  "Burpee",
  "Battle Ropes",
  "Rowing Machine",
  "Running",
  "Cycling",
  "Jump Rope",
  "Stair Climber",
];

export const COMMON_TAGS = [
  "Push",
  "Pull",
  "Legs",
  "Upper Body",
  "Lower Body",
  "Full Body",
  "Chest",
  "Back",
  "Shoulders",
  "Arms",
  "Core",
  "Glutes",
  "Hamstrings",
  "Quads",
  "Calves",
  "Cardio",
  "HIIT",
  "Strength",
  "Powerlifting",
  "Olympic Lifting",
  "Bodyweight",
  "Mobility",
  "Warmup",
  "Recovery",
];
